-- This file creates the space schema for Oracle databases.');
-- DO NOT MODIFY THIS FILE.  It is automatically generated.');

-- #1: Session settings.
alter session set nls_timestamp_format = 'YYYY-MM-DD HH24MISS';


  CREATE TABLE "ORGANIZATION" 
   (	"ORG_CODE" VARCHAR2(9), 
	"ORG_NAME" VARCHAR2(81), 
	"ORG_CLASS" VARCHAR2(29), 
	"PARENT_ORG_CODE" VARCHAR2(13), 
	"ORG_STATE_CODE" VARCHAR2(7), 
	"ORG_LOCATION" VARCHAR2(53), 
	"ORG_START_DATE" DATE, 
	"ORG_STOP_DATE" DATE, 
	"ORG_UTF8_NAME" VARCHAR2(230), 
	 CONSTRAINT "ORGANIZATION_PK" PRIMARY KEY ("ORG_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PLATFORM" 
   (	"PLATFORM_CODE" VARCHAR2(11), 
	"PLATFORM_UCODE" VARCHAR2(12), 
	"PLATFORM_STATE_ORG_CODE" VARCHAR2(8), 
	"PLATFORM_TYPE" VARCHAR2(17), 
	"PLATFORM_CLASS" VARCHAR2(29), 
	"PLATFORM_SHORT_NAME" VARCHAR2(18), 
	"PLATFORM_NAME" VARCHAR2(81), 
	"PLATFORM_PARENT_ORG_CODE" VARCHAR2(13), 
	 CONSTRAINT "PLATFORM_PK" PRIMARY KEY ("PLATFORM_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PLATFORM_STATE_FK" FOREIGN KEY ("PLATFORM_STATE_ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE, 
	 CONSTRAINT "PLATFORM_PARENT_FK" FOREIGN KEY ("PLATFORM_PARENT_ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE
   ) ;

  CREATE TABLE "ORGANIZATION_ORG_TYPE" 
   (	"ORG_CODE" VARCHAR2(9), 
	"ORG_TYPE" VARCHAR2(4000), 
	 CONSTRAINT "ORGANIZATION_ORG_FK" FOREIGN KEY ("ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE
   ) ;

  CREATE TABLE "SITE" 
   (	"SITE_ID" NUMBER, 
	"SITE_NAME" VARCHAR2(9), 
	"SITE_CODE" VARCHAR2(13), 
	"SITE_TYPE" VARCHAR2(32), 
	"STATE_ORG_CODE" VARCHAR2(9), 
	"START_DATE" DATE, 
	"STOP_DATE" DATE, 
	"SITE_SHORT_NAME" VARCHAR2(18), 
	"SITE_FULL_NAME" VARCHAR2(81), 
	"SITE_LOCATION" VARCHAR2(53), 
	"LONGITUDE" NUMBER, 
	"LATITUDE" NUMBER, 
	"DEGREES_UNCERTAINTY" NUMBER, 
	 CONSTRAINT "SITE_PK" PRIMARY KEY ("SITE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SITE_ORG_FK" FOREIGN KEY ("STATE_ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE
   ) ;

  CREATE TABLE "SITE_ORG" 
   (	"SITE_ID" NUMBER, 
	"ORG_CODE" VARCHAR2(4000), 
	 CONSTRAINT "SITE_ORG_PK" PRIMARY KEY ("SITE_ID", "ORG_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SITE_ORG_SITE_FK" FOREIGN KEY ("SITE_ID")
	  REFERENCES "SITE" ("SITE_ID") ENABLE, 
	 CONSTRAINT "SITE_ORG_ORG_FK" FOREIGN KEY ("ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE
   ) ;

  CREATE TABLE "LAUNCH_VEHICLE_FAMILY" 
   (	"LV_FAMILY_CODE" VARCHAR2(21), 
	"LV_FAMILY_CLASS" VARCHAR2(28), 
	 CONSTRAINT "LAUNCH_VEHICLE_FAMILY_PK" PRIMARY KEY ("LV_FAMILY_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "LAUNCH_VEHICLE" 
   (	"LV_ID" NUMBER, 
	"LV_NAME" VARCHAR2(33), 
	"LV_VARIANT" VARCHAR2(11), 
	"LV_CLASS" VARCHAR2(37), 
	"LV_FAMILY_CODE" VARCHAR2(21), 
	"LV_ALIAS" VARCHAR2(20), 
	"MIN_STAGE" NUMBER, 
	"MAX_STAGE" NUMBER, 
	"LENGTH" VARCHAR2(6), 
	"DIAMETER" VARCHAR2(6), 
	"LAUNCH_MASS" VARCHAR2(9), 
	"LEO_CAPACITY" VARCHAR2(9), 
	"GTO_CAPACITY" VARCHAR2(9), 
	"TAKE_OFF_THRUST" VARCHAR2(9), 
	"APOGEE" VARCHAR2(7), 
	"RANGE" VARCHAR2(6), 
	 CONSTRAINT "LAUNCH_VEHICLE_PK" PRIMARY KEY ("LV_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LAUNCH_VEHICLE_UJ" UNIQUE ("LV_NAME", "LV_VARIANT")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LAUNCH_VEHICLE_FAMILY_FK" FOREIGN KEY ("LV_FAMILY_CODE")
	  REFERENCES "LAUNCH_VEHICLE_FAMILY" ("LV_FAMILY_CODE") ENABLE
   ) ;

  CREATE TABLE "LAUNCH_VEHICLE_MANUFACTURER" 
   (	"LV_ID" NUMBER, 
	"LV_MANUFACTURER_ORG_CODE" VARCHAR2(4000), 
	 CONSTRAINT "LAUNCH_VEHICLE_MAN_ORG_PK" PRIMARY KEY ("LV_ID", "LV_MANUFACTURER_ORG_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LAUNCH_VEHICLE_MAN_ORG_FK" FOREIGN KEY ("LV_MANUFACTURER_ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE
   ) ;

  CREATE TABLE "LAUNCH" 
   (	"LAUNCH_ID" NUMBER, 
	"LAUNCH_TAG" VARCHAR2(15), 
	"LAUNCH_DATE" DATE, 
	"LAUNCH_CATEGORY" VARCHAR2(31), 
	"LAUNCH_STATUS" VARCHAR2(31), 
	"LV_ID" NUMBER, 
	"FLIGHT_ID1" VARCHAR2(21), 
	"FLIGHT_ID2" VARCHAR2(25), 
	"MISSION" VARCHAR2(25), 
	"FLIGHTCODE" VARCHAR2(25), 
	"FLIGHT_TYPE" VARCHAR2(25), 
	"SITE_ID" NUMBER, 
	"PLATFORM_CODE" VARCHAR2(10), 
	"APOGEE" VARCHAR2(7), 
	 CONSTRAINT "LAUNCH_PK" PRIMARY KEY ("LAUNCH_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LAUNCH_LV_FK" FOREIGN KEY ("LV_ID")
	  REFERENCES "LAUNCH_VEHICLE" ("LV_ID") ENABLE, 
	 CONSTRAINT "LAUNCH_SITE_FK" FOREIGN KEY ("SITE_ID")
	  REFERENCES "SITE" ("SITE_ID") ENABLE, 
	 CONSTRAINT "LAUNCH_PLATFORM_FK" FOREIGN KEY ("PLATFORM_CODE")
	  REFERENCES "PLATFORM" ("PLATFORM_CODE") ENABLE
   ) ;

  CREATE TABLE "LAUNCH_PAYLOAD_ORG" 
   (	"LAUNCH_ID" NUMBER, 
	"PAYLOAD_ORG_CODE" VARCHAR2(4000), 
	 CONSTRAINT "LAUNCH_PAYLOAD_ORG_PK" PRIMARY KEY ("LAUNCH_ID", "PAYLOAD_ORG_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LAUNCH_PAYLOAD_ORG_LAUNCH_FK" FOREIGN KEY ("LAUNCH_ID")
	  REFERENCES "LAUNCH" ("LAUNCH_ID") ENABLE, 
	 CONSTRAINT "LAUNCH_PAYLOAD_ORG_ORG_FK" FOREIGN KEY ("PAYLOAD_ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE
   ) ;

  CREATE TABLE "LAUNCH_AGENCY" 
   (	"LAUNCH_ID" NUMBER, 
	"AGENCY_ORG_CODE" VARCHAR2(4000), 
	 CONSTRAINT "LAUNCH_AGENCY_PK" PRIMARY KEY ("LAUNCH_ID", "AGENCY_ORG_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LAUNCH_AGENCY_LAUNCH_FK" FOREIGN KEY ("LAUNCH_ID")
	  REFERENCES "LAUNCH" ("LAUNCH_ID") ENABLE, 
	 CONSTRAINT "LAUNCH_AGENCY_ORG_FK" FOREIGN KEY ("AGENCY_ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE
   ) ;

  CREATE TABLE "SATELLITE" 
   (	"NORAD" VARCHAR2(28), 
	"COSPAR" VARCHAR2(15), 
	"OFFICIAL_NAME" VARCHAR2(41), 
	"SECONDARY_NAME" VARCHAR2(25), 
	"LAUNCH_ID" NUMBER, 
	"CURRENT_STATUS" VARCHAR2(17), 
	"STATUS_DATE" DATE, 
	"ORBIT_DATE" DATE, 
	"ORBIT_PERIOD" NUMBER, 
	"PERIGEE" NUMBER, 
	"APOGEE" NUMBER, 
	"INCLINATION" NUMBER, 
	"ORBIT_CLASS" VARCHAR2(35), 
	 CONSTRAINT "SATELLITE_PK" PRIMARY KEY ("NORAD")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SATELLITE_FK" FOREIGN KEY ("LAUNCH_ID")
	  REFERENCES "LAUNCH" ("LAUNCH_ID") ENABLE
   ) ;

  CREATE TABLE "SATELLITE_ORG" 
   (	"NORAD" VARCHAR2(28), 
	"OWNER_OPERATOR_ORG_CODE" VARCHAR2(4000), 
	 CONSTRAINT "SATELLITE_ORG_PK" PRIMARY KEY ("NORAD", "OWNER_OPERATOR_ORG_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SATELLITE_ORG_SAT_FK" FOREIGN KEY ("NORAD")
	  REFERENCES "SATELLITE" ("NORAD") ENABLE, 
	 CONSTRAINT "SATELLITE_ORG_ORG_FK" FOREIGN KEY ("OWNER_OPERATOR_ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE
   ) ;

  CREATE TABLE "ENGINE" 
   (	"ENGINE_ID" NUMBER, 
	"ENGINE_NAME" VARCHAR2(21), 
	"ENGINE_FAMILY" VARCHAR2(21), 
	"ENGINE_ALT_NAME" VARCHAR2(13), 
	"FIRST_LAUNCH_YEAR" NUMBER, 
	"USAGE" VARCHAR2(20), 
	"MASS" NUMBER, 
	"IMPULSE" NUMBER, 
	"THRUST" NUMBER, 
	"SPECIFIC_IMPULSE" NUMBER, 
	"DURATION" NUMBER, 
	"CHAMBER_COUNT" NUMBER, 
	 CONSTRAINT "ENGINE_PK" PRIMARY KEY ("ENGINE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "STAGE" 
   (	"STAGE_NAME" VARCHAR2(21), 
	"STAGE_FAMILY" VARCHAR2(21), 
	"STAGE_ALT_NAME" VARCHAR2(21), 
	"LENGTH" NUMBER, 
	"DIAMETER" NUMBER, 
	"LAUNCH_MASS" NUMBER, 
	"DRY_MASS" NUMBER, 
	"THRUST" NUMBER, 
	"DURATION" NUMBER, 
	"ENGINE_ID" NUMBER, 
	"ENGINE_COUNT" NUMBER, 
	 CONSTRAINT "STAGE_PK" PRIMARY KEY ("STAGE_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "STAGE_ENGINE_FK" FOREIGN KEY ("ENGINE_ID")
	  REFERENCES "ENGINE" ("ENGINE_ID") ENABLE
   ) ;

  CREATE TABLE "LAUNCH_VEHICLE_STAGE" 
   (	"LV_ID" NUMBER, 
	"STAGE_NAME" VARCHAR2(21), 
	"STAGE_NO" VARCHAR2(3), 
	"IS_DUMMY" NUMBER, 
	"MULTIPLICITY" NUMBER, 
	"STAGE_IMPULSE" NUMBER, 
	"STAGE_APOGEE" NUMBER, 
	"STAGE_PERIGEE" NUMBER, 
	 CONSTRAINT "LAUNCH_VEHICLE_STAGE_PK" PRIMARY KEY ("LV_ID", "STAGE_NAME", "STAGE_NO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LAUNCH_VEHICLE_STAGE_FK1" FOREIGN KEY ("LV_ID")
	  REFERENCES "LAUNCH_VEHICLE" ("LV_ID") ENABLE, 
	 CONSTRAINT "LAUNCH_VEHICLE_STAGE_FK2" FOREIGN KEY ("STAGE_NAME")
	  REFERENCES "STAGE" ("STAGE_NAME") ENABLE
   ) ;

  CREATE TABLE "STAGE_MANUFACTURER" 
   (	"STAGE_NAME" VARCHAR2(21), 
	"MANUFACTURER_ORG_CODE" VARCHAR2(4000), 
	 CONSTRAINT "STAGE_MANUFACTURER_PK" PRIMARY KEY ("STAGE_NAME", "MANUFACTURER_ORG_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "STAGE_MANUFACTURER_STAGE_FK" FOREIGN KEY ("STAGE_NAME")
	  REFERENCES "STAGE" ("STAGE_NAME") ENABLE, 
	 CONSTRAINT "STAGE_MANUFACTURER_MANUF_FK" FOREIGN KEY ("MANUFACTURER_ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE
   ) ;

  CREATE TABLE "PROPELLENT" 
   (	"PROPELLENT_ID" NUMBER, 
	"PROPELLENT_NAME" VARCHAR2(4000), 
	 CONSTRAINT "PROPELLENT_PK" PRIMARY KEY ("PROPELLENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PROPELLENT_UK" UNIQUE ("PROPELLENT_NAME")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ENGINE_PROPELLENT" 
   (	"ENGINE_ID" NUMBER, 
	"PROPELLENT_ID" NUMBER, 
	"OXIDIZER_OR_FUEL" VARCHAR2(8), 
	 CONSTRAINT "ENGINE_PROPELLENT_PK" PRIMARY KEY ("ENGINE_ID", "PROPELLENT_ID", "OXIDIZER_OR_FUEL")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ENGINE_PROPELLENT_ENGINE_FK" FOREIGN KEY ("ENGINE_ID")
	  REFERENCES "ENGINE" ("ENGINE_ID") ENABLE, 
	 CONSTRAINT "ENGINE_PROPELLENT_PROP_FK" FOREIGN KEY ("PROPELLENT_ID")
	  REFERENCES "PROPELLENT" ("PROPELLENT_ID") ENABLE
   ) ;

  CREATE TABLE "ENGINE_MANUFACTURER" 
   (	"ENGINE_ID" NUMBER, 
	"MANUFACTURER_ORG_CODE" VARCHAR2(4000), 
	 CONSTRAINT "ENGINE_MANUFACTURER_PK" PRIMARY KEY ("ENGINE_ID", "MANUFACTURER_ORG_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ENGINE_MANUFACTURER_ENGINE_FK" FOREIGN KEY ("ENGINE_ID")
	  REFERENCES "ENGINE" ("ENGINE_ID") ENABLE, 
	 CONSTRAINT "ENGINE_MANUFACTURER_MANUF_FK" FOREIGN KEY ("MANUFACTURER_ORG_CODE")
	  REFERENCES "ORGANIZATION" ("ORG_CODE") ENABLE
   ) ;
